{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "yourbiz-static.serviceAccountName" . }}
  labels:
{{ include "yourbiz-static.labels" . | nindent 4 }}
{{- end -}}
