---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-backup-volume
  labels:
    volume: nfs-backup-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "my-nfs-server"
    path: "/my/nfs/jenkins-test"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-backup-volume-claim
  namespace: pks-testbed
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      volume: nfs-backup-volume
