replicaCount: 1

image:
  repository: registry.yourdomain.com/yourbiz/yourbiz-api
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

## @start yourbiz be 配置
serverPort: 80
serverTimezone: Asia/Shanghai
jarFile: biz-api.jar

## application.yaml 以及额外的 ConfigMap
applicationConfigMap:
  mountPath: /etc/yourbiz
  extra: |-
    key: value
# externalConfigMap 的 mountPath 与 applicationConfigMap 中一致
externalConfigMap:
  enabled: true
  name: config.xml
  mountPath: /etc/yourbiz
  content: |-
    key: value

localFileStore:
  enabled: true
  savePath: /yourbiz/files
  maxFileSize: 1024MB
  endpoint: https://api.yourdomain.com/file
oss:
  # accessKeyId:
  # accessKeySecret:
  # endpoint: oss-cn-hangzhou.aliyuncs.com
  bucketName: yourbiz-dev
  expiration: 900
  maxSize: 17179869184
  callbackUrl: https://api.yourdomain.com/callback/oss
secret:
  {}
  # jwt:
  #   secret:
wechat:
  enabled: false
  # token:
  # appId:
  # appSecret:
dingTalk:
  {}
  # accessToken:

## MySQL 配置
mysql:
  enabled: true
  timezone: Asia/Shanghai

  imageTag: 8.0.18

externalMySql: {}

## Redis 配置
redis:
  enabled: true
  address: ""
  password: ""

## RabbitMQ 配置
rabbitmq:
  enabled: false
  virtualHost: /dev
  ## permission issue
  securityContext:
    enabled: true
    runAsUser: 0
    fsGroup: 2000

## @end yourbiz be 配置

persistence:
  enabled: false
  # existingClaim:
  # annotations:
  # accessMode:
  # size:
  # storageClass:

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
