{{- $fullName := include "yourbiz-be.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "yourbiz-be.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "yourbiz-be.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "yourbiz-be.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "yourbiz-be.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- if .Values.mysql.enabled }}
        - name: check-mysql-ready
          image: {{ .Values.mysql.image | default "mysql" }}:{{ .Values.mysql.imageTag | default "8" }}
          command: ['sh', '-c',
          'until mysqladmin --connect-timeout 2 ping -h{{ $fullName }}-mysql -P{{ .Values.mysql.service.port | default 3306 }} -u{{ .Values.mysql.username }} -p$MYSQL_PASSWORD | grep "mysqld is alive"; do echo waiting for mysql; sleep 2; done;']
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.mysql.enabled }}
                  name: {{ $fullName }}-mysql
                  {{- else }}
                  name: {{ $fullName }}
                  {{- end }}
                  key: mysql-password
        {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["java"]
          args: ["-Duser.timezone={{ .Values.serverTimezone }}", "-jar", {{ .Values.jarFile }}, "--spring.config.location={{ .Values.applicationConfigMap.mountPath }}/application.yaml"]
          ports:
            - name: http
              # see secret.yaml server.port
              containerPort: {{ .Values.serverPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: app-conf
              mountPath: {{ .Values.applicationConfigMap.mountPath }}
              readOnly: true
            {{- if .Values.externalConfigMap.enabled }}
            - name: app-extra-conf
              mountPath: {{ .Values.externalConfigMap.mountPath }}
              readOnly: true
            {{- end }}
            - name: yourbiz-local-file-storage
              mountPath: {{ .Values.localFileStore.savePath }}
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.mysql.enabled }}
                  name: {{ $fullName }}-mysql
                  {{- else }}
                  name: {{ $fullName }}
                  {{- end }}
                  key: mysql-password
            {{- if .Values.rabbitmq.enabled }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: rabbitmq-password
            {{- end }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: jwt-secret
            - name: OSS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: oss-access-key-id
            - name: OSS_ACCESS_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: oss-access-key-secret
            {{- if .Values.wechat.enabled }}
            - name: WECHAT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: wechat-token
            - name: WECHAT_APP_SECRET              
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: wechat-app-secret
            {{- end }}
          startupProbe:
            httpGet:
              path: /swagger-resources
              port: http
            failureThreshold: 30
            periodSeconds: 10
      volumes:
        - name: app-conf
          configMap:
            name: {{ $fullName }}
        - name: app-extra-conf
          configMap:
            name: {{ $fullName }}-extra
        - name: yourbiz-local-file-storage
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default $fullName }}
          {{- else }}
          emptyDir: {}
          {{- end }}      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
