{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "yourbiz-be.serviceAccountName" . }}
  labels:
{{ include "yourbiz-be.labels" . | nindent 4 }}
{{- end -}}
