{{- if .Values.customCaddyfile.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yourbiz-static.fullname" . }}
  labels:
    {{- include "yourbiz-static.labels" . | nindent 4 }}
data:
  Caddyfile: |
    {{ .Values.customCaddyfile.content | nindent 4 }}
{{- end }}
