---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-denny
# Create service account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-privileged-sa
  namespace: ns-denny
---
# create privileged-psp
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged-psp
  namespace: ns-denny
spec:
  fsGroup:
    rule: RunAsAny
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
  allowedCapabilities:
  - '*'
  hostPID: true
  hostIPC: true
  hostNetwork: true
  hostPorts:
  - min: 1
    max: 65536
---
# Create role with certain psp
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:role-privileged-sa
  namespace: ns-denny
rules:
  - apiGroups:
      - extensions
    resourceNames:
      - privileged-psp
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
# Bind role to service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:bind-privileged-sa
  namespace: ns-denny
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:role-privileged-sa
subjects:
  - kind: ServiceAccount
    name: test-privileged-sa
