{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ufc-static.serviceAccountName" . }}
  labels:
{{ include "ufc-static.labels" . | nindent 4 }}
{{- end -}}
