sharedVolumes:
  - name: shared-data
    emptyDir: {}

initContainers:
  - name: init
    image: debian
    volumeMounts:
      - name: shared-data
        mountPath: /pod-data
    command: ["/bin/sh"]
    args:
      - "-c"
      - >
        date >> /pod-data/index.html;
        echo Hello world from init container >> /pod-data/index.html;

sharedVolumeMounts:
  - name: shared-data
    mountPath: /srv

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging-cluster"
  hosts:
    - host: echo1.test.unionfab.com
      paths:
        - /
  tls:
    - secretName: echo1.test.unionfab.com
      hosts:
        - echo1.test.unionfab.com

customCaddyfile:
  enabled: false
  content: |
    0.0.0.0
    browse
    log stdout
    errors stdout
    header {
      # enable HSTS
      Strict-Transport-Security max-age=31536000;

      # disable clients from sniffing the media type
      X-Content-Type-Options nosniff
      
      # clickjacking protection
      X-Frame-Options DENY

      # keep referrer data off of HTTP connections
      Referrer-Policy no-referrer-when-downgrade
    }
