# https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
# https://cheatsheet.dennyzhang.com/kubernetes-yaml-templates
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: gke-cluster-1-default-pool-559d6680-43r5
  backoffLimit: 4
