# https://kubernetes.io/docs/tasks/administer-cluster/limit-storage-consumption/
# In this example, a 6th PVC in the namespace would be rejected because it exceeds the maximum count of 5. 
# https://cheatsheet.dennyzhang.com/kubernetes-yaml-templates
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storagequota
spec:
  hard:
    persistentvolumeclaims: "5"
    requests.storage: "5Gi"
